"""Source registry: every data origin used by ParlaySports.

Each entry records URL, access method, cost, license, reliability,
granularity, depth, verification date, status and limitations -- the fields
required by the platform spec. No paid APIs. No trials.
"""
from __future__ import annotations

import sqlite3

REGISTRY: list[dict[str, str]] = [
    {
        "source_id": "SRC_NFLVERSE_GAMES",
        "name": "nflverse nfldata game schedules, scores & lines",
        "url": "https://github.com/nflverse/nfldata/blob/master/data/games.csv",
        "data_type": "NFL schedules, final scores, spreads/totals/moneylines, weather, QBs, rest",
        "access_method": "git clone / raw CSV download (public, no key)",
        "cost": "Free (MIT/CC-BY)",
        "license": "MIT / CC-BY-4.0",
        "reliability": "5/5 - curated by nflverse; cross-verified this build vs ESPN/DK + Kalshi",
        "granularity": "game level, 1999-2026",
        "historical_depth": "1999-2026 schedules+scores; market lines 2006-2025 (+2026 current)",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_PRIMARY",
        "limitations": "Preseason excluded. Lines are consensus snapshots, not tick data. 2006/2008 partial line coverage.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_ESPN_SCOREBOARD",
        "name": "ESPN scoreboard API (all four leagues)",
        "url": "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard",
        "data_type": "Schedules, live/final scores, records, DraftKings odds blocks (upcoming NFL verified)",
        "access_method": "keyless HTTPS GET",
        "cost": "Free (unofficial endpoint; ESPN ToS apply)",
        "license": "ESPN terms; facts re-stated, no redistribution of media",
        "reliability": "4/5 - official score data; odds block present for upcoming games only",
        "granularity": "game level; per-day query",
        "historical_depth": "Rolling current season via dates= param; no historical odds",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_PRIMARY",
        "limitations": "No historical odds (verified negative, matches NHLComp finding). Unofficial API may change.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_KALSHI",
        "name": "Kalshi public market data API (trade-api v2)",
        "url": "https://api.elections.kalshi.com/trade-api/v2/markets",
        "data_type": "Regulated-exchange binary prices: KXNFLGAME, KXNHLGAME/SPREAD/TOTAL/OVERTIME, KXNBAGAME; candles/orderbooks",
        "access_method": "keyless HTTPS GET (public market data)",
        "cost": "Free",
        "license": "Kalshi public market data (keyless endpoints)",
        "reliability": "5/5 for quotes - CFTC-regulated exchange tape",
        "granularity": "contract level, cent ticks, hourly candles",
        "historical_depth": "live tier (recent) + /historical tier (settled before cutoff)",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_PRIMARY",
        "limitations": "Winner markets only per game (no spreads/totals except NHL ladders). NO side publishes no offer on some contracts. MLB series (KXMLBGAME) not yet confirmed by this build.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_MLB_STATSAPI",
        "name": "MLB Stats API (official league feed)",
        "url": "https://statsapi.mlb.com/api/v1/schedule",
        "data_type": "Official schedule, scores, standings, splits, probable pitchers",
        "access_method": "keyless HTTPS GET",
        "cost": "Free",
        "license": "MLBAM terms (copyright notice retained)",
        "reliability": "5/5 - league of record",
        "granularity": "game level + team splits + expected records",
        "historical_depth": "Full history queryable by date range",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_PRIMARY",
        "limitations": "Schedule endpoint carries no odds. 2026 game-level log backfill runs in nightly collector.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_NHL_API",
        "name": "NHL official API (api-web.nhle.com + partner feed)",
        "url": "https://api-web.nhle.com/v1/schedule/now",
        "data_type": "Schedule, scores, team stats; partner-game DraftKings odds snapshots",
        "access_method": "keyless HTTPS GET",
        "cost": "Free",
        "license": "NHL terms",
        "reliability": "5/5 scores; 4/5 partner odds (reference snapshots)",
        "granularity": "game level",
        "historical_depth": "Schedules/scores back many seasons; odds snapshots forward-only from 2026-09-20",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_PRIMARY",
        "limitations": "Partner odds are reference lines, not a full book. Preseason split-squad games flagged.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_SBR_NBA",
        "name": "SportsbookReview NBA odds archive (via NBAComp hist_odds)",
        "url": "https://www.sportsbookreviewsonline.com/scoresoddsarchives/nba-odds-2013-14",
        "data_type": "Historical NBA open/close spreads, totals, moneylines + final scores",
        "access_method": "imported snapshot from sibling repo NBAComp (data/nbacomp.db hist_odds)",
        "cost": "Free",
        "license": "SBR terms; single-source snapshot",
        "reliability": "3/5 - single source, NOT cross-checked (cross_checked=0 upstream)",
        "granularity": "game level; October-December slices per season",
        "historical_depth": "2013-14 .. 2022-23 (Oct-Dec only, 4,043 games)",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "SINGLE_SOURCE",
        "limitations": "Partial seasons (Oct-Dec). Not cross-verified. Used for NBA backtests with grade capped at REFERENCE.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_SIBLING_NBACOMP",
        "name": "Sibling repo NBAComp game log + forward lines",
        "url": "https://github.com/buffedlizard55-lab/NBAComp",
        "data_type": "NBA games 2024-27 (ESPN/BRef), 2026-27 schedule, ESPN/DK forward lines, Kalshi opener markets",
        "access_method": "git clone (public repo)",
        "cost": "Free",
        "license": "Repo terms; upstream sources ESPN/BRef/Kalshi",
        "reliability": "4/5 - re-validated on import; scores spot-checked",
        "granularity": "game level",
        "historical_depth": "2024-25, 2025-26 finals; 2026-27 scheduled",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_SECONDARY",
        "limitations": "Inherited snapshot; nightly collector re-verifies against ESPN.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_SIBLING_NHLCOMP",
        "name": "Sibling repo NHLComp games + Kalshi price points",
        "url": "https://github.com/buffedlizard55-lab/NHLComp",
        "data_type": "NHL games 2024-27, team map, Kalshi GAME/SPREAD/TOTAL closes, DK partner snapshots",
        "access_method": "git clone (public repo)",
        "cost": "Free",
        "license": "Repo terms; upstream sources NHL/Kalshi",
        "reliability": "4/5 - re-validated on import",
        "granularity": "game level + contract level",
        "historical_depth": "2024-25, 2025-26 full; 2026-27 preseason + scheduled",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_SECONDARY",
        "limitations": "Inherited snapshot; 2026-27 regular-season game count anomaly flagged (1344 vs expected 1312).",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_SIBLING_MLB_RESULTS",
        "name": "Sibling repo MLB-Prediction-model-backtest results 2015-2025",
        "url": "https://github.com/buffedlizard55-lab/MLB-Prediction-model-backtest",
        "data_type": "MLB game results 2015-2025 (from official StatsAPI via MLB-PBP tooling)",
        "access_method": "git clone (public repo)",
        "cost": "Free",
        "license": "Repo terms; upstream official MLB data",
        "reliability": "4/5 - re-validated on import (score sanity, schedule counts)",
        "granularity": "game level, no odds",
        "historical_depth": "2015-2025 regular seasons",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_SECONDARY",
        "limitations": "No odds: MLB backtests are outcome/signal only unless model-priced (labeled MODEL).",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_SIBLING_VACSCHED",
        "name": "Sibling repo VacationSchedule verified MLB/NFL fixtures",
        "url": "https://github.com/buffedlizard55-lab/VacationSchedule",
        "data_type": "2026 MLB fixture list (game_pks, times) + 2026 NFL schedule, with provenance manifests",
        "access_method": "git clone (public repo)",
        "cost": "Free",
        "license": "Repo terms; upstream StatsAPI",
        "reliability": "4/5",
        "granularity": "game level fixtures (no scores)",
        "historical_depth": "2026 season fixtures",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "VERIFIED_SECONDARY",
        "limitations": "Fixtures only. Times subject to league rescheduling.",
        "provenance_class": "SOURCE_DATA",
    },
    {
        "source_id": "SRC_MODEL",
        "name": "ParlaySports internal models (Elo, Pythag/log5, totals estimators)",
        "url": "https://github.com/buffedlizard55-lab/ParlaySports",
        "data_type": "Derived probabilities and fair prices computed from verified scores",
        "access_method": "computed in-repo (parlaysports/ratings.py)",
        "cost": "Free",
        "license": "Same repo",
        "reliability": "MODEL OUTPUT - not market data, never presented as such",
        "granularity": "game level",
        "historical_depth": "as far as score inputs reach",
        "last_verified_utc": "2026-09-22T01:00:00Z",
        "status": "MODEL",
        "limitations": "Estimates with error bars unknown; used for MODEL-grade legs only.",
        "provenance_class": "MODEL_OUTPUT",
    },
]


def install_registry(con: sqlite3.Connection) -> int:
    n = 0
    for s in REGISTRY:
        con.execute(
            """INSERT OR REPLACE INTO sources(source_id, name, url, data_type, access_method,
               cost, license, reliability, granularity, historical_depth,
               last_verified_utc, status, limitations, provenance_class)
               VALUES (:source_id, :name, :url, :data_type, :access_method, :cost, :license,
               :reliability, :granularity, :historical_depth, :last_verified_utc, :status,
               :limitations, :provenance_class)""",
            s,
        )
        n += 1
    return n
